fix: cmd-79 favicon missing but in settings export
Fix this error
```
django_settings_export.UndefinedSettingError: "settings.FAVICON" is included in settings.SETTINGS_EXPORT but it does not exist.
```

Caused by FAVICON not used by a project, yet Core-CMS was still trying to export it.