refactor: cmd-79 rename tacc cms settings (#792)
* refactor: cmd-79 `PORTAL_` not `TACC_` ⚠️ UNTESTED

* chore: remove duplicate property (and value)

* docs: tv3-181, logo property mapping

* docs(upgrade-project): cmd-79/tv3-181

* docs(upgrade-project): append "+" to 4.7 and 3.12

* docs: abandon "Rename Certain Other Settings"

* refactor: cmd-79 `INCLUDES_` `SEARCH_` ⚠️ UNTESTED

* docs(upgrade-project): add "update custom favicon setting"

* docs(upgrade-project): use diff for logo/favicon

* style: cmd-79 move `is_remote` property

* docs(upgrade-project): fix bad target / h3 link

* fix(taccsite_custom): bad submodule merge resolve

* docs: cmd-79 upgrade use of favicon in templates

* docs: cmd-79 settings rename to be in v4.9 not 4.8

v4.8 was released while this was still in progress.

* fix: cmd-79 favicon missing but in settings export

Fix this error
```
django_settings_export.UndefinedSettingError: "settings.FAVICON" is included in settings.SETTINGS_EXPORT but it does not exist.
```

Caused by FAVICON not used by a project, yet Core-CMS was still trying to export it.

* fix: cmd-79 logo missing from settings export

Fix this error
```
The `LOGO` setting key is not accessible from templates: add "LOGO" to `settings.SETTINGS_EXPORT` to change that.
```

Caused by LOGO backwards compatibility neglecting SETTINGS_EXPORT.

* fix: cmd-79 backwards-compatibility must read imports (UNTESTED)

* fix: cmd-79 simpler backwards-compatibility (UNTESTED)

* fix: cmd-79 backwards-compatibility loop bug (UNTESTED)

* fix: cmd-79 backwards-compatibility typo (UNTESTED)

* fix: cmd-79 backwards-compatibility if missing settings

* feat: CMD-79 custom nav width via PORTAL_NAV_WIDTH

* fix: CMD-79 core-styles bug appears with custom nav width

* Revert "feat: CMD-79 custom nav width via PORTAL_NAV_WIDTH"

This reverts commit 5d459d101a7c00885baad56876525313b10963f7.

* fix: backwards compatibility code typos

* feat: CMD-79 custom nav width via PORTAL_NAV_WIDTH (#837)

* refactor: PORTAL_IS_CORE → PORTAL_MANAGES_AUTH

* style: rename SHOW_ vars in header.html

* refactor: …_MANAGES_AUTH → …_IS_TACC_CORE_PORTAL

* docs: 4.12 (not 4.9) will rename settings

* fix: only swap TACC_ with PORTAL_ if necessary

* feat: backwards-compatible INCLUDES_ and SEARCH_

* style: move settings (so PORTAL_'s are together)

* fix: server crash / missing LOGO setting key

> The `LOGO` setting key is not accessible from templates: add "LOGO" to `settings.SETTINGS_EXPORT` to change that.

> `{% if settings.LOGO %}`

* chore: remove cruft comment

* style: no new line in deprecated settings code

* fix: example settings rename

* test: package.json version v4.12.0-beta.5

Maybe this will update site_cms/css/build/site.app.blog.css…