Moved all the deps forward a bit. Cleaned up the requirements.txt files and package.json files to reflect correct dependencies after updates.
Python deps were updated using the pip-upgrader package to resolve dependency graph conflicts and then run against the 2020 pi validation check as follows:

$ pip install --use-feature=2020-resolver -r requirements.txt
Requirement already satisfied: aldryn-apphooks-config==0.6.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: asgiref==3.2.10 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (3.2.10)
Requirement already satisfied: astroid==2.4.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.4.2)
Requirement already satisfied: certifi==2020.6.20 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2020.6.20)
Requirement already satisfied: chardet==3.0.4 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: colorclass==2.2.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (2.2.0)
Requirement already satisfied: Django==2.2.16 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2.2.16)
Requirement already satisfied: django-appconf==1.0.4 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.0.4)
Requirement already satisfied: django-appdata==0.3.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (0.3.0)
Requirement already satisfied: django-classy-tags==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: django-cms==3.7.4 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (3.7.4)
Requirement already satisfied: django-filer==2.0.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (2.0.2)
Requirement already satisfied: django-formtools==2.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (2.2)
Requirement already satisfied: django-ipware==3.0.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (3.0.1)
Requirement already satisfied: django-js-asset==1.2.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (1.2.2)
Requirement already satisfied: django-meta==1.7.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (1.7.0)
Requirement already satisfied: django-mptt==0.11.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (0.11.0)
Requirement already satisfied: django-parler==2.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (2.2)
Requirement already satisfied: django-polymorphic==3.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (3.0.0)
Requirement already satisfied: django-sekizai==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (2.0.0)
Requirement already satisfied: django-settings-export==1.2.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (1.2.1)
Requirement already satisfied: django-sortedm2m==3.0.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 22)) (3.0.2)
Requirement already satisfied: django-taggit==1.3.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 23)) (1.3.0)
Requirement already satisfied: django-taggit-autosuggest==0.3.8 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 24)) (0.3.8)
Requirement already satisfied: django-taggit-templatetags==0.2.5 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 25)) (0.2.5)
Requirement already satisfied: django-templatetag-sugar==1.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 26)) (1.0)
Requirement already satisfied: django-treebeard==4.3.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 27)) (4.3.1)
Requirement already satisfied: djangocms-admin-style==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 28)) (2.0.0)
Requirement already satisfied: djangocms-apphook-setup==0.4.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 29)) (0.4.1)
Requirement already satisfied: djangocms-attributes-field==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 30)) (2.0.0)
Requirement already satisfied: djangocms-blog==1.1.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 31)) (1.1.1)
Requirement already satisfied: djangocms-bootstrap4==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 32)) (2.0.0)
Requirement already satisfied: djangocms-column==1.11.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 33)) (1.11.0)
Requirement already satisfied: djangocms-file==3.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 34)) (3.0.0)
Requirement already satisfied: djangocms-googlemap==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 35)) (2.0.0)
Requirement already satisfied: djangocms-icon==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 36)) (2.0.0)
Requirement already satisfied: djangocms-link==3.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 37)) (3.0.0)
Requirement already satisfied: djangocms-page-meta==0.10.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 38)) (0.10.0)
Requirement already satisfied: djangocms-picture==3.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 39)) (3.0.0)
Requirement already satisfied: djangocms-snippet==3.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 40)) (3.0.0)
Requirement already satisfied: djangocms-style==3.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 41)) (3.0.0)
Requirement already satisfied: djangocms-text-ckeditor==3.10.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 42)) (3.10.0)
Requirement already satisfied: djangocms-video==3.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 43)) (3.0.0)
Requirement already satisfied: docopt==0.6.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 44)) (0.6.2)
Requirement already satisfied: easy-thumbnails==2.7 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 45)) (2.7)
Requirement already satisfied: gunicorn==20.0.4 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 46)) (20.0.4)
Requirement already satisfied: hashids==1.3.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 47)) (1.3.1)
Requirement already satisfied: html5lib==1.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 48)) (1.1)
Requirement already satisfied: idna==2.10 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 49)) (2.10)
Requirement already satisfied: isort==5.5.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 50)) (5.5.2)
Requirement already satisfied: lazy-object-proxy==1.5.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 51)) (1.5.1)
Requirement already satisfied: lxml==4.5.2 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 52)) (4.5.2)
Requirement already satisfied: mccabe==0.6.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 53)) (0.6.1)
Requirement already satisfied: packaging==20.4 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 54)) (20.4)
Requirement already satisfied: Pillow==7.2.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 55)) (7.2.0)
Requirement already satisfied: pip-upgrader==1.4.15 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 56)) (1.4.15)
Requirement already satisfied: psycopg2==2.8.6 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 57)) (2.8.6)
Requirement already satisfied: psycopg2-binary==2.8.6 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 58)) (2.8.6)
Requirement already satisfied: pylint==2.6.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 59)) (2.6.0)
Requirement already satisfied: pyparsing==2.4.7 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 60)) (2.4.7)
Requirement already satisfied: pytz==2020.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 61)) (2020.1)
Requirement already satisfied: requests==2.24.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 62)) (2.24.0)
Requirement already satisfied: six==1.15.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 63)) (1.15.0)
Requirement already satisfied: sqlparse==0.3.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 64)) (0.3.1)
Requirement already satisfied: tablib==2.0.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 65)) (2.0.0)
Requirement already satisfied: terminaltables==3.1.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 66)) (3.1.0)
Requirement already satisfied: toml==0.10.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 67)) (0.10.1)
Requirement already satisfied: Unidecode==1.1.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 68)) (1.1.1)
Requirement already satisfied: urllib3==1.25.10 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 69)) (1.25.10)
Requirement already satisfied: webencodings==0.5.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 70)) (0.5.1)
Requirement already satisfied: wrapt==1.12.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 71)) (1.12.1)
Requirement already satisfied: django-cms==3.7.4 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (3.7.4)
Requirement already satisfied: django-appdata==0.3.0 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (0.3.0)
Requirement already satisfied: wrapt==1.12.1 in /Users/jgentle/miniconda3/envs/tacc.wma.sad.cms.upgrade/lib/python3.8/site-packages (from -r requirements.txt (line 71)) (1.12.1)
ERROR: Cannot install lazy-object-proxy==1.5.1 and astroid 2.4.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested lazy-object-proxy==1.5.1
    astroid 2.4.2 depends on lazy-object-proxy==1.4.*

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

This is atop these pinned packages:

pip-upgrade --skip-virtualenv-check
Found valid requirements file(s):
requirements.txt
1/71: aldryn-apphooks-config ... up to date: 0.6.0
2/71: asgiref ... up to date: 3.2.10
3/71: astroid ... up to date: 2.4.2
4/71: certifi ... up to date: 2020.6.20
5/71: chardet ... up to date: 3.0.4
6/71: colorclass ... up to date: 2.2.0
7/71: Django ... upgrade available: 2.2.16 ==> 3.1.1 (uploaded on 2020-09-01 09:14:32)
8/71: django-appconf ... up to date: 1.0.4
9/71: django-appdata ... up to date: 0.3.0
10/71: django-classy-tags ... up to date: 2.0.0
11/71: django-cms ... up to date: 3.7.4
12/71: django-filer ... up to date: 2.0.2
13/71: django-formtools ... up to date: 2.2
14/71: django-ipware ... up to date: 3.0.1
15/71: django-js-asset ... up to date: 1.2.2
16/71: django-meta ... up to date: 1.7.0
17/71: django-mptt ... up to date: 0.11.0
18/71: django-parler ... up to date: 2.2
19/71: django-polymorphic ... up to date: 3.0.0
20/71: django-sekizai ... up to date: 2.0.0
21/71: django-settings-export ... up to date: 1.2.1
22/71: django-sortedm2m ... up to date: 3.0.2
23/71: django-taggit ... up to date: 1.3.0
24/71: django-taggit-autosuggest ... up to date: 0.3.8
25/71: django-taggit-templatetags ... up to date: 0.2.5
26/71: django-templatetag-sugar ... up to date: 1.0
27/71: django-treebeard ... up to date: 4.3.1
28/71: djangocms-admin-style ... up to date: 2.0.0
29/71: djangocms-apphook-setup ... up to date: 0.4.1
30/71: djangocms-attributes-field ... up to date: 2.0.0
31/71: djangocms-blog ... up to date: 1.1.1
32/71: djangocms-bootstrap4 ... up to date: 2.0.0
33/71: djangocms-column ... up to date: 1.11.0
34/71: djangocms-file ... up to date: 3.0.0
35/71: djangocms-googlemap ... up to date: 2.0.0
36/71: djangocms-icon ... up to date: 2.0.0
37/71: djangocms-link ... up to date: 3.0.0
38/71: djangocms-page-meta ... up to date: 0.10.0
39/71: djangocms-picture ... up to date: 3.0.0
40/71: djangocms-snippet ... up to date: 3.0.0
41/71: djangocms-style ... up to date: 3.0.0
42/71: djangocms-text-ckeditor ... up to date: 3.10.0
43/71: djangocms-video ... up to date: 3.0.0
44/71: docopt ... up to date: 0.6.2
45/71: easy-thumbnails ... up to date: 2.7
46/71: gunicorn ... up to date: 20.0.4
47/71: hashids ... up to date: 1.3.1
48/71: html5lib ... up to date: 1.1
49/71: idna ... up to date: 2.10
50/71: isort ... up to date: 5.5.2
51/71: lazy-object-proxy ... up to date: 1.5.1
52/71: lxml ... up to date: 4.5.2
53/71: mccabe ... up to date: 0.6.1
54/71: packaging ... up to date: 20.4
55/71: Pillow ... up to date: 7.2.0
56/71: pip-upgrader ... up to date: 1.4.15
57/71: psycopg2 ... up to date: 2.8.6
58/71: psycopg2-binary ... up to date: 2.8.6
59/71: pylint ... up to date: 2.6.0
60/71: pyparsing ... up to date: 2.4.7
61/71: pytz ... up to date: 2020.1
62/71: requests ... up to date: 2.24.0
63/71: six ... up to date: 1.15.0
64/71: sqlparse ... up to date: 0.3.1
65/71: tablib ... up to date: 2.0.0
66/71: terminaltables ... up to date: 3.1.0
67/71: toml ... up to date: 0.10.1
68/71: Unidecode ... up to date: 1.1.1
69/71: urllib3 ... up to date: 1.25.10
70/71: webencodings ... up to date: 0.5.1
71/71: wrapt ... up to date: 1.12.1

Available upgrades:
+-----+----------+-----------------+----------------+---------------------+
| No. | Package  | Current version | Latest version | Release date        |
+-----+----------+-----------------+----------------+---------------------+
|  1  |  Django  | 2.2.16          | 3.1.1          | 2020-09-01 09:14:32 |
+-----+----------+-----------------+----------------+---------------------+