chore: tup-677 css/django/vite interoperability (#780)
* chore: tup-677 css/django/vite interoperability (#778)

* chore: tup-677 no commented @import statements

* refactor: tup-677 no absolute /static paths in css

Testing:
1. Verify `c-island` style still works in WYSIWYG editor.

* chore: tup-677 install related core-styles branch

* staticfiles works with manifest backend

* chore: tup-677 install latest core-styles branch

* docs: collectstatic " --ignore assets/*/font*.css"

This need for this is to avoid an error introuduced by tup-677.

```log
Post-processing 'ui/assets/generics/fonts.css' failed!

…

ValueError: The file 'ui/assets/generics/fonts/BentonSans-Regular.otf' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7ffffc9b5280>.
```

---------

Co-authored-by: Jake Rosenberg <jrosenberg@tacc.utexas.edu>

* fix: no STORAGE settings cuz Core is not ready yet

* chore: tup-677 install latest core-styles release

* Revert "docs: collectstatic " --ignore assets/*/font*.css""

This reverts commit 476895d449ff58bc438e669910954fc8d01fc03a.

* docs: collectstatic no " --ignore"

The settign that caused this extra step was moved to tup-ui, so Core-CMS would still work.

* fix(utrc): WP-135 support deploy with CMS v3.12

* chore(taccsite_custom): merge chore/tup-677-…

---------

Co-authored-by: Jake Rosenberg <jrosenberg@tacc.utexas.edu>